import { trpc } from "@/utils/trpc";
import styled from "styled-components";
import Head from "next/head";

const StyledUserItem = styled.li`
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  gap: 0.1rem;
`;

export default function Home() {
  const { data, isLoading, error } = trpc.user.getUsers.useQuery();

  if (isLoading) return <h1>Loading...</h1>;
  if (error) return <h1>{error.message}</h1>;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ul>
        {data &&
          data.map((user) => (
            <StyledUserItem key={user.id}>
              <h1>User {user.name}</h1>
              <p>
                Email: <strong>{user.email}</strong>
              </p>
            </StyledUserItem>
          ))}
      </ul>
    </>
  );
}
